name: Generate README.md

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v3

      - name: Setup Vlang environment
        uses: vlang/setup-v@v1.1

      - name: Run a one-line script (building the script and exeuting the .exe would be useless for a mere script)
        run: v run gen-readme.v

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
