name: Generate README.md

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checks-out your repository
        uses: actions/checkout@v3

      # - name: Setup Vlang environment --> Bad it copy the entire vlang repo into your repo ???
      #   uses: vlang/setup-v@v1.1

      - name: Run a one-line script
        # run: v run gen-readme.v
        run: gen-readme.exe

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
